In [ ]:
import torch
import numpy as np
from scipy.optimize import minimize
from modele import *
from visualisation import *
from pytorch_optim import *
%load_ext autoreload
%autoreload 2


In [ ]:
N=3
nb_colonnes_default = 50
T = 300
L = 5
params = {
    "N": N,  # nombre de couches
    "L": L,  # longueur du bassin
    "H": 1,  # hauteur du bassin
    "nb_colonnes_default": 50,  # discrétisation horizontale
    "D": 1e-5,  # coefficient de diffusion
    "T": T,  # temps final pour 20 tours
    "CFL": 0.95,  # facteur CFL
    "u" : [0.01]*N,
    "I_s": 1500,
    "epsilon": 4.6,
    "k_d": 2.99e-4,   # 2.99*10e-5 = 2.99e-4
    "k_r": 4.8e-4,    # 4.8*10e-5 = 4.8e-4
    "k_h": 3.64e-4,   # 3.64*10e-5 = 3.64e-4
    "tau": 6.849,
    "sigma_H": 2.9e-3,  # 2.9*10e-4 = 2.9e-3
    "theta": 3.64e-4 * 2.9e-3,  # k_h * sigma_H
    "I_star": np.sqrt(4.8e-4 / (2.99e-4 * 6.849 * (2.9e-3)**2)),
    "mu_max": 3.64e-4 * 2.9e-3 / (6.849 * 2.9e-3 + 2*np.sqrt((2.99e-4 * 6.849 * (2.9e-3)**2)/4.8e-4))
}

In [ ]:
params["N"] = 5
P, biomass_list = solve(X_ini_one_layer_torch(5, nb_colonnes_default), T, params)
print(f'P : {P}')
print(f'biomass list : {biomass_list}')
X = X_ini_one_layer(N, nb_colonnes_default)
masse_totale, M, liste_biomasses= meilleure_matrice_de_permutation(X, T, params)
print(f'best permutation matrix : {M}')
print(f'masse totale : {masse_totale}')

0 50.37870788574219


KeyboardInterrupt: 

In [7]:
print(params)

{'N': 3, 'L': 5, 'H': 1, 'nb_colonnes_default': 50, 'D': 1e-05, 'T': 300, 'CFL': 0.95, 'u': [0.01, 0.01, 0.01], 'I_s': 1500, 'epsilon': 4.6, 'k_d': 0.000299, 'k_r': 0.00048, 'k_h': 0.000364, 'tau': 6.849, 'sigma_H': 0.0029, 'theta': 1.0556e-06, 'I_star': np.float64(166.94501039780602), 'mu_max': np.float64(3.315108749636504e-05)}


In [11]:
N_lignes = params["N"]
Q = torch.nn.Parameter(torch.randn(N_lignes, N_lignes))
def J(Q):
    P = torch.softmax(Q, dim=0)
    return(fonction_objectif_torch(X_ini_one_layer_torch(N_lignes, nb_colonnes_default), T, P, params))

Q_sol = Newton(J, Q, N_lignes**2)
print(torch.softmax(Q_sol, dim=0))

tensor([[ 1.2573e-06, -5.7626e-09, -1.2522e-08],
        [-4.1337e-04,  1.7800e-06,  4.2194e-06],
        [ 4.1238e-04, -1.7045e-06, -4.2469e-06]], grad_fn=<SubBackward0>)
tensor([[ 2.2155e-06, -8.8027e-09, -2.2916e-08],
        [-4.1623e-04,  1.7838e-06,  4.2331e-06],
        [ 4.1422e-04, -1.7043e-06, -4.2481e-06]], grad_fn=<SubBackward0>)
tensor([[ 2.5056e-06, -1.0008e-08, -2.5834e-08],
        [-4.1666e-04,  1.7845e-06,  4.2351e-06],
        [ 4.1456e-04, -1.7042e-06, -4.2483e-06]], grad_fn=<SubBackward0>)
tensor([[ 2.5824e-06, -1.0327e-08, -2.6604e-08],
        [-4.1644e-04,  1.7840e-06,  4.2336e-06],
        [ 4.1458e-04, -1.7042e-06, -4.2483e-06]], grad_fn=<SubBackward0>)
tensor([[ 2.6000e-06, -1.0400e-08, -2.6782e-08],
        [-4.1648e-04,  1.7837e-06,  4.2328e-06],
        [ 4.1448e-04, -1.7042e-06, -4.2484e-06]], grad_fn=<SubBackward0>)
tensor([[ 2.6028e-06, -1.0416e-08, -2.6821e-08],
        [-4.1659e-04,  1.7835e-06,  4.2323e-06],
        [ 3.8133e-04, -1.7018e-06, -4.2606

In [ ]:
params["N"] = 10
params["u"] = [0.01]*10
N_lignes = 10
Q = torch.nn.Parameter(torch.randn(N_lignes, N_lignes))
def J(Q):
    P = torch.softmax(Q, dim=0)
    return(fonction_objectif_torch(X_ini_one_layer_torch(N_lignes, nb_colonnes_default), T, P, params))

Q_sol = Newton(J, Q, N_lignes**2)
print(torch.softmax(Q_sol, dim=0))

NameError: name 'params' is not defined